### ISSUE TITLE
Return code execution time rather than just printing

### ISSUE THREAD

**Issue by mr-vaibh** [mr-vaibh/python-code-execution-time#1]
Create a function that returns execution time, in milliseconds by default, but shall also accept parameters to return in seconds.

**Comment by Aadi1101** [comment]
I want to work on this issue can you assign this issue to me

**Comment by mr-vaibh** [comment]
> I want to work on this issue can you assign this issue to me

yeah sure, you are assigned 👍

**Comment by Aadi1101** [comment]
`import datetime
def func(seconds=False):

    start_time = datetime.datetime.now()
    end_time = datetime.datetime.now()
#your code here
    time_diff = (end_time - start_time)
    execution_time = time_diff.total_seconds() *0.001
    if (seconds==False):
        pass
    else:

        end_time = datetime.datetime.now()

        time_diff = (end_time - start_time)
        execution_time_seconds = time_diff.total_seconds()
        return(execution_time,'- in milliseconds & in seconds - ',execution_time_seconds) 

    return('execution time in milliseconds - ',execution_time)

z=func(seconds=True)
print(z)`

**Comment by Aadi1101** [comment]
import datetime
def func(seconds=False):

    start_time = datetime.datetime.now()
    end_time = datetime.datetime.now()
#your code here
    time_diff = (end_time - start_time)
    execution_time = time_diff.total_seconds() *0.001
    if (seconds==False):
        pass
    else:

        end_time = datetime.datetime.now()

        time_diff = (end_time - start_time)
        execution_time_seconds = time_diff.total_seconds()
        return(execution_time,'- in milliseconds & in seconds - ',execution_time_seconds) 

    return('execution time in milliseconds - ',execution_time)

z=func(seconds=True)
print(z)

**Comment by mr-vaibh** [comment]
> import datetime def func(seconds=False):
> 
> ```
> start_time = datetime.datetime.now()
> end_time = datetime.datetime.now()
> ```
> 
> #your code here time_diff = (end_time - start_time) execution_time = time_diff.total_seconds() *0.001 if (seconds==False): pass else:
> 
> ```
>     end_time = datetime.datetime.now()
> 
>     time_diff = (end_time - start_time)
>     execution_time_seconds = time_diff.total_seconds()
>     return(execution_time,'- in milliseconds & in seconds - ',execution_time_seconds) 
> 
> return('execution time in milliseconds - ',execution_time)
> ```
> 
> z=func(seconds=True) print(z)

nice efforts, keep it up, it would be much better and easier for me if you could just make a Pull Request

**Comment by mr-vaibh** [comment]
@Aadi1101 I see this is your first contribution

Although I've accepted your PR, still there were some issues with your commit, like..
 - functionality had to be added in `__init__.py` file
 - the function was supposed to be a decorator
 - some general practices to be followed like leave 1 or 2 lines after import statements, nice indentations, code readability
 
But hey, this is not some GIGANTIC project so I decided to accept it anyway. I'll make some amendments on my own.
Thanks 😄

**Comment by Aadi1101** [comment]
Thank you sir and I will definitely work on the points you mentioned
